name: Submit to Winget Community Repo

on:
  release:
    types: published
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: The release tag to submit
        required: true

jobs:
  winget:
    if: ${{ github.repository_owner == 'Vencord' }}
    name: Publish winget package (${{ matrix.identifier == 'Vendicated.Vencord' && 'Stable' || matrix.identifier == 'Vendicated.Vencord.PTB' && 'PTB' || matrix.identifier == 'Vendicated.Vencord.Canary' && 'Canary' }})
    runs-on: windows-latest
    strategy:
      matrix:
        identifier:
          - Vendicated.Vencord
          - Vendicated.Vencord.PTB
          - Vendicated.Vencord.Canary

    steps:
      - name: Submit package to Winget Community Repo
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: ${{ matrix.identifier }}
          token: ${{ secrets.WINGET_PAT }}
          installers-regex: 'VencordInstallerCli-Windows-x64\.exe'
          release-tag: ${{ inputs.tag || github.event.release.tag_name }}
          fork-user: shiggybot
